# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command and `artifact-name` to assign a name to
# distinguish build outputs from each other:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#     shield: corne_left
#     cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#     artifact-name: corne_left_with_logging
#
---
include:
  # Original Corne (for wireless Cygnus build)
#  - board: nice_nano_v2
#    shield: corne_left
#  - board: nice_nano_v2
#    shield: corne_right

#  - board: nice_nano_v2
#    shield: sweep_central_left led_indicator
#    artifact-name: sweep_central_left

#  - board: nice_nano_v2
#    shield: sweep_central_left led_indicator
#    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#    artifact-name: sweep_central_left_with_logging

  # rommana
  - board: nice_nano_v2
    shield: rommana_central_dongle dongle_display
    artifact-name: rommana_central_dongle
  - board: nice_nano_v2
    shield: rommana_peripheral_left led_indicator
    artifact-name: rommana_peripheral_left
  - board: nice_nano_v2
    shield: rommana_peripheral_right led_indicator
    artifact-name: rommana_peripheral_right
  - board: nice_nano_v2
    shield: rommana_central_dongle dongle_display
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: rommana_central_dongle_with_logging
#  - board: nice_nano_v2
#    shield: rommana_central_left led_indicator
#    artifact-name: rommana_central_left

  # Original Sweep/Cradio
#  - board: nice_nano_v2
#    shield: cradio_left
#  - board: nice_nano_v2
#    shield: cradio_right
  # Englmaxi sweep
#  - board: nice_nano_v2
#    shield: sweep_central_dongle dongle_display
#    artifact-name: sweep_central_dongle
#  - board: nice_nano_v2
#    shield: sweep_peripheral_left led_indicator
#    artifact-name: sweep_peripheral_left
#  - board: nice_nano_v2
#    shield: sweep_peripheral_right led_indicator
#    artifact-name: sweep_peripheral_right

  # reset
  - board: nice_nano_v2
    shield: settings_reset

